# Generated by Django 4.2.16 on 2025-06-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('reclamo', 'Reclamo'), ('felicitacion', 'Felicitación')], max_length=15)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
